---
title: "Final Project"
author: "Michelle Lam"
date: "2022-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load all the packages needed here
library(tidyverse)
library(readr)
library(gt)
library(tufte)
library(feasts)
library(tidycensus)
library(janitor) #used to clean up column names
library(lubridate) #used to convert column values to date/dateime

# Set your filepath here! Or, set this up as an .Rproj if you'd like.
rootdir <- ("/Users/michelle/Documents/UCSB Grad School/Courses/eds_222")
setwd(file.path(rootdir,"eds222_final_project"))
datadir <-(file.path(rootdir, "eds222_final_project","data"))

census_token <- Sys.getenv('CENSUS_KEY')
census_api_key(census_token)
```

### SGIP Data Wrangling

```{r}
#read in the SGIP data
sgip <- read_csv(file.path(datadir,"sgip_weekly_data.csv")) |> 
  janitor::clean_names()

#filter down to rebates for just residential electrochemcial storage that were not cancelled, 2020 year
#look into difference between residential and single family/multi-family
sgip_res_battery <- sgip |> 
  filter(equipment_type == "Electrochemical Storage", host_customer_sector == "Residential", budget_classification != "Cancelled") |>
  select("city", "county", "zip", "date_received") |> 
  mutate("date_received" = str_sub(date_received, 1, 8)) |> 
  mutate("date_received" = as.Date(date_received, format = "%m/%d/%y")) |>
  mutate("year_received" = year(date_received)) |>
  mutate("month_received" = month(date_received)) |> 
  filter(year_received == 2020) |> 
  mutate("zip" = ifelse(
    str_length(zip) == 10, 
    substring(zip, 1, nchar(zip)-5),
    zip))

#create summary data frame showing number of applications by zip code
sgip_zip <- sgip_res_battery |> 
  group_by(zip) |> 
  summarize(count = n())
```

### Exploratory Data Visualization of SGIP Data

```{r}
top_sgip_zip <- sgip_zip |> 
  slice_max(n = 10, order_by = count) |> 
  gt()

top_sgip_zip
```

### Census Data Wrangling

```{r}
#access ACS data variables for 2020 year 
v20 <- load_variables(2020, "acs5", cache = TRUE)
View(v20)

#read in per capita income data for census tracts in CA
ca_pc_income_tract <- get_acs(geography = "tract",
                            variables = c(percapita_income = "B19301_001"),
                            state = "CA",
                            year = 2020)

#clean and format per capita income data frame
ca_pc_income_tract_clean <- ca_pc_income_tract |> 
  select(c("GEOID", "NAME", "estimate")) |> 
  rename(percapita_income = "estimate")

#read in population data for census tracts in CA
ca_pop_tract <- get_acs(geography = "tract",
                        variables = c(population = "B01003_001"),
                        state = "CA",
                        year = 2020)

#clean and format population data frame 
ca_pop_tract_clean <- ca_pop_tract |> 
  select(c("GEOID", "NAME", "estimate")) |> 
  rename(population = "estimate")

#combine per capita income and population data frames
combine_census <- cbind(ca_pc_income_tract_clean, ca_pop_tract_clean$population) |> 
  rename(population = "ca_pop_tract_clean$population", tract = "GEOID")

```

### Crosswalk File 
```{r}
#read in crosswalk file to use when matching zip codes to
crosswalk <- read_csv(file.path(datadir,"ZIP_TRACT_122020.csv")) |> 
  janitor::clean_names()

#add zipcode from crosswalk file to combined census file
# census_with_zip <- left_join(combine_census, crosswalk, by = "tract") |> 
#   select(c("tract", "NAME", "percapita_income", "population", "zip"))
```

### Combine Datasets
```{r}
#add census tracts to sgip_zip
sgip_zip_census <- left_join(sgip_zip, crosswalk, by = "zip") |> 
  mutate("count_adjusted" = count*res_ratio) #now we have theoretical count of applications per census tract
#because there are multiple census tracts for one zip code, use the res_ratio to allocate what portion of the count of SGIP applications should be allocated to one census tract

#make sure the count_adjusted worked by filtering down to one zipcode
zip_90004 <- sgip_zip_census |> 
  filter(zip == 90004)

#combine everything together
combined_all <- left_join(sgip_zip_census, combine_census, by = "tract") |> 
  mutate("percapita_application" = count_adjusted/population) |> 
  mutate("income_group" = ifelse(percapita_income <= 48800, "low income", "not low income")) #low income in CA for 2020 48,800 threshold

#effect of income categories on SGIP applications over time 
#effect of income categories on rate of SGIP applications
#crosswalk data files to match up zip codes with census tracts
#on average just take one year
#population from ACS, higher income areas have more people
#applications per capita on income per capita 
#look at more recent years for SGIP resiliency


```

### Visualize Data

```{r}
ggplot(data = combined_all) +
  geom_point(aes(x = percapita_income, y = percapita_application)) +
  labs(x = "Per Capita Income", y = "Per Capita Application", title = "SGIP Applications Per Capita and Income Per Capita (2020)") +
  theme_minimal()
```

### Run Linear Regression
```{r}
model = lm(percapita_application ~ percapita_income, data = combined_all)
summary(model)

R2 = summary(model)$r.squared
R2
```

```{r}
#unique counties
county_list <- sgip_res_battery |> 
  group_by(county) |> 
  summarize(count = n()) |> 
  select(c("county", "count"))

#find the counties with the most sgip applications
top_sgip_county <- sgip_res_battery |> 
  group_by(county) |> 
  summarize(count = n()) |> 
  slice_max(n = 10, order_by = count)

#create a data frame that shows number of sgip applications per year in each of the top 10 counties
sgip_uptake <- sgip_res_battery |>
  filter(county %in% top_sgip_county$county) |> 
  group_by(month_received, county) |> 
  summarize(count = n())

#make a plot to show uptake across the different counties
ggplot(data = sgip_uptake) +
  geom_line(aes(x = month_received, y = count, col = county)) +
  scale_x_continuous(breaks = seq(ceiling(min(sgip_uptake$month_received)), floor(max(sgip_uptake$month_received)), by = 2)) +
  labs(x = "Month SGIP Application Received", y = "Number of SGIP Applications", title = "SGIP Applications for top 10 CA Counties (2020)") +
  theme_minimal()
```
